
import { GoogleGenAI, Modality } from "@google/genai";
import type { UploadedImage } from '../types';

/**
 * Generates an image using the Gemini API based on a text prompt and an optional reference image.
 *
 * @param prompt The text prompt describing the desired image.
 * @param image An optional object containing the base64 data and MIME type of a reference image.
 * @returns A promise that resolves to the base64 string of the generated image.
 */
export async function generateImage(
  prompt: string,
  image?: UploadedImage | null
): Promise<string> {
  // IMPORTANT: The API key is accessed from environment variables.
  // Do not expose this key on the client-side in a production application.
  // This implementation assumes the key is available in the execution environment.
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable not set.");
  }
  
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const parts: ({ text: string } | { inlineData: { data: string; mimeType: string; } })[] = [];

  if (image) {
    parts.push({
      inlineData: {
        data: image.data,
        mimeType: image.mimeType,
      },
    });
  }

  if (prompt) {
    parts.push({ text: prompt });
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: { parts },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the API.");
}
